[package]
name = "circuit"
version = "0.1.0"
edition = "2024"
default-run = "main"

[dependencies]
bitvec = { version = "1.0.1" }
petgraph = { version = "0.8.2", optional = true }

[features]
# default = [ ]
default = [ "graph" ]
graph = [ "petgraph" ]
